### PR TITLE
NPE repair of admin module caused by spring MVC example synchronization

### LINKED ISSUE #3446: [BUG] Spring MVC example synchronization will cause the admin module doc to process NPE
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
ShenYu version(s):2.5.0
```

### Debug logs

2022-05-28 15:50:58 [shenyu-scheduled-upstream-task-1] INFO  org.apache.shenyu.admin.service.manager.impl.LoadServiceDocEntryImpl - loadDocOnSelectorChanged serviceList=[{"contextPath":"/mvc","ip":"172.16.1.50","port":8289,"startupTime":1653724258052,"healthy":true,"enabled":true,"clusterName":"mvc"}]
2022-05-28 15:51:00 [shenyu-scheduled-upstream-task-1] ERROR org.apache.shenyu.admin.service.manager.impl.DocManagerImpl - getDocInfo error={}
java.lang.NullPointerException: null
	at org.apache.shenyu.admin.service.manager.impl.SwaggerDocParser.parseJson(SwaggerDocParser.java:59)
	at org.apache.shenyu.admin.service.manager.impl.DocManagerImpl.getDocInfo(DocManagerImpl.java:99)
	at org.apache.shenyu.admin.service.manager.impl.DocManagerImpl.addDocInfo(DocManagerImpl.java:81)
	at org.apache.shenyu.admin.service.manager.impl.ServiceDocManagerImpl.pullApiDocument(ServiceDocManagerImpl.java:72)
	at org.apache.shenyu.admin.service.manager.impl.ServiceDocManagerImpl.lambda$pullApiDocument$0(ServiceDocManagerImpl.java:53)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.shenyu.admin.service.manager.impl.ServiceDocManagerImpl.pullApiDocument(ServiceDocManagerImpl.java:52)
	at org.apache.shenyu.admin.service.manager.impl.LoadServiceDocEntryImpl.loadDocOnSelectorChanged(LoadServiceDocEntryImpl.java:82)
	at org.apache.shenyu.admin.listener.DataChangedEventDispatcher.onApplicationEvent(DataChangedEventDispatcher.java:66)
	at org.apache.shenyu.admin.listener.DataChangedEventDispatcher.onApplicationEvent(DataChangedEventDispatcher.java:39)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	at org.apache.shenyu.admin.service.impl.UpstreamCheckService.updateSelectorHandler(UpstreamCheckService.java:310)
	at org.apache.shenyu.admin.service.impl.UpstreamCheckService.updateHandler(UpstreamCheckService.java:281)
	at org.apache.shenyu.admin.service.impl.UpstreamCheckService.lambda$submit$3(UpstreamCheckService.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

### Anything else?

e28671a6bbc71ea1770ee4da521bbed
3b1f9631de93d3c038e36e670681a7b

### PR DESCRIPTION
**Pull request by renzhuyan**
// Describe your PR here; eg. Fixes #3446

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

File: shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/impl/SwaggerDocParser.java [hunk 1]
```diff
@@ -56,7 +56,7 @@ public class SwaggerDocParser implements DocParser {
     @Override
     public DocInfo parseJson(final JSONObject docRoot) {
         final String basePath = docRoot.getString("basePath");
-        final String title = docRoot.getJSONObject("info").getString("title");
+        final String title = Optional.ofNullable(docRoot.getJSONObject("info")).map(jsonObject -> jsonObject.getString("title")).orElse("");
```
Comment (dragon-zhang) [inline shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/impl/SwaggerDocParser.java:59]: @lianjunwei please give a default `title` value.

Comment (renzhuyan) [reply shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/impl/SwaggerDocParser.java]: I will fix it

**Review by dragon-zhang — APPROVED** [review]
