### PR TITLE
fix: NPE when refreshURIService

### LINKED ISSUE #1814: NPE when start application with nacos register center
image

### PR DESCRIPTION
**Pull request by YXxy1002**
Fixed #1814 

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor/).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

File: shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java [hunk 1]
```diff
@@ -165,7 +165,11 @@ private void publishMetadata(final String data) {
     }
 
     private void refreshURIService(final RpcTypeEnum rpcType, final String serviceName) {
-        for (String contextPath: uriServiceCache.get(serviceName)) {
+        ConcurrentSkipListSet<String> services = uriServiceCache.get(serviceName);
+        if (services == null) {
```
Comment (tydhot) [inline shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java:169]: I think 
````
if (services != null) {
 .....
}
````
would be better

**Review by dengliming — DISMISSED** [review]

File: shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java (hunk 1 above)
Comment (dengliming) [reply shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java:169]: It's fine for me. can avoid adding a layer of `if` nesting

Comment (tydhot) [reply shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java:169]: nop, I mean use if (services != null)  instead of 
````
if (services == null) {
    return;
}
````
The code will be cleaner.

**Review by lw1243925457 — DISMISSED** [review]
It's also fine for me.

File: shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java (hunk 1 above)
Comment (KevinClair) [reply shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java:169]: Agree, or you can use `optional`.

Comment (YXxy1002) [reply shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java:169]: maybe in this way?
`
ConcurrentSkipListSet<String> services = uriServiceCache.get(serviceName);
        Optional.ofNullable(services).ifPresent(data -> {
            for (String contextPath : data) {
                registerURI(contextPath, serviceName, rpcType);
            }
});
`

Comment (YXxy1002) [reply shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java:169]: maybe in this way?

```java
ConcurrentSkipListSet<String> services = uriServiceCache.get(serviceName);
Optional.ofNullable(services).ifPresent(data -> {
    for (String contextPath : data) {
        registerURI(contextPath, serviceName, rpcType);
    }
});
```

Comment (yu199195) [reply shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java:169]: maybe like this :

```java

        Optional.ofNullable(uriServiceCache.get(serviceName)).ifPresent(services -> services.forEach(contextPath-> registerURI(contextPath, serviceName, rpcType)));

```

**Comment by yu199195** [comment]
Can you fix the other IDEA warnings for this class?

File: shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java (hunk 1 above)
Comment (yu199195) [reply shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java:169]: Can you fix the other IDEA warnings for this class?

Comment (YXxy1002) [reply shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java]: It's all settled

**Review by tydhot — APPROVED** [review]

**Review by yu199195 — APPROVED** [review]
