### PR TITLE
[ISSUE #2443] Improve the stability of Ratelimiter plugin integration test

### LINKED ISSUE #2443: [Volunteer] Improve the stability of Ratelimiter plugin integration test
### Volunteer help

Integrated test of RateLimiterPlugin sometimes run failed, such as https://github.com/apache/incubator-shenyu/runs/4307259601?check_suite_focus=true .

### PR DESCRIPTION
**Pull request by JooKS-me**
Fix #2443 .

### CODE REVIEW

File: shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RateLimiterPluginTest.java [hunk 1]
```diff
@@ -67,7 +67,7 @@ public void testSlidingWindow() throws IOException, ExecutionException, Interrup
         AdminResponse<Object> dto = rejectedRespFuture.get();
         assertEquals("You have been restricted, please try again later!", dto.getMessage());
 
-        Thread.sleep(1000);
+        Thread.sleep(5000);
```
Comment (yu199195) [inline shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RateLimiterPluginTest.java:70]: whats mean？

Comment (JooKS-me) [reply shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RateLimiterPluginTest.java:70]: @yu199195 Because replenishRate was set 0.2, we need to wait 5 seconds to be allowed.

Comment (JooKS-me) [reply shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RateLimiterPluginTest.java:70]: replenishRate was set 0.2 to reduce the probability of errors

**Review by yu199195 — APPROVED** [review]
